"""Reviewer Agent: Evaluates the Generator's output for quality and appropriateness."""

import json
from typing import Optional
from openai import OpenAI


class ReviewerAgent:
    """
    Evaluates educational content generated by the Generator Agent.
    Checks for age appropriateness, conceptual correctness, and clarity.
    """

    def __init__(self, api_key: Optional[str] = None):
        self.client = OpenAI(api_key=api_key)
        self.model = "gpt-4o-mini"

    def review(self, grade: int, topic: str, content: dict) -> dict:
        """
        Evaluate generated educational content against quality criteria.

        Args:
            grade: Target grade level for the content.
            topic: Subject topic of the content.
            content: Generator output containing 'explanation' and 'mcqs'.

        Returns:
            Dict with 'status' ("pass" or "fail") and 'feedback' (list of strings).
        """
        if not isinstance(content, dict) or "explanation" not in content or "mcqs" not in content:
            return {
                "status": "fail",
                "feedback": ["Invalid content structure provided to reviewer"]
            }

        prompt = self._build_prompt(grade, topic, content)

        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[{"role": "user", "content": prompt}],
                temperature=0.3,
            )
            review_content = response.choices[0].message.content
            return self._parse_response(review_content)
        except Exception as e:
            return {
                "status": "fail",
                "feedback": [f"Review failed: {str(e)}"]
            }

    def _build_prompt(self, grade: int, topic: str, content: dict) -> str:
        """Construct the evaluation prompt from the generated content."""
        explanation = content.get("explanation", "")
        mcqs = content.get("mcqs", [])

        mcqs_text = ""
        for i, mcq in enumerate(mcqs, 1):
            options = ", ".join(mcq.get("options", []))
            answer = mcq.get("answer", "?")
            mcqs_text += f"\nQuestion {i}: {mcq.get('question', '')}\n"
            mcqs_text += f"Options: {options}\n"
            mcqs_text += f"Answer: {answer}\n"

        return f"""You are an expert educational content reviewer. Evaluate the following educational content created for Grade {grade} students on the topic: "{topic}".

CONTENT TO REVIEW:

Explanation:
{explanation}

MCQs:
{mcqs_text}

Evaluation Criteria:
1. Age Appropriateness: Is the language, complexity, and content suitable for Grade {grade}?
2. Conceptual Correctness: Are all concepts factually accurate and correctly explained?
3. Clarity: Is the explanation clear and understandable? Are questions unambiguous?

Rules:
- Be critical but fair
- If you find issues, be SPECIFIC about exact sentences or questions that are problematic
- If content is suitable, return "pass" status with optional minor suggestions
- If content has significant issues, return "fail" status with detailed feedback

Return ONLY valid JSON (no markdown, no code blocks):
{{
    "status": "pass" or "fail",
    "feedback": [
        "Specific feedback item 1",
        "Specific feedback item 2"
    ]
}}

If status is "pass", feedback can be empty or contain minor suggestions."""

    def _parse_response(self, content: str) -> dict:
        """
        Parse the review response into a structured result.

        Args:
            content: Raw string response from the LLM.

        Returns:
            Dict with validated 'status' and 'feedback' fields.
        """
        content = content.strip()
        if content.startswith("```json"):
            content = content[7:]
        if content.startswith("```"):
            content = content[3:]
        if content.endswith("```"):
            content = content[:-3]

        try:
            result = json.loads(content.strip())
        except json.JSONDecodeError as e:
            return {
                "status": "fail",
                "feedback": [f"Failed to parse review response: {str(e)}"]
            }

        if "status" not in result or "feedback" not in result:
            return {
                "status": "fail",
                "feedback": ["Review response missing required fields"]
            }

        if result["status"] not in ("pass", "fail"):
            return {
                "status": "fail",
                "feedback": [f"Invalid review status: {result['status']}"]
            }

        if not isinstance(result["feedback"], list):
            result["feedback"] = [str(result["feedback"])]

        return result
